### ISSUE TITLE
Variable declaration and initialization can be done within for loop declaration

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/english-to-braille-js-assignment-problem-vermarahul18#1]
https://github.com/sro-boeing-wave-2/english-to-braille-js-assignment-problem-vermarahul18/blob/61103b74ae6c501529ba9b98edd24ba617c0344f/index.js#L15-L16

**Comment by vermarahul18** [comment]
Variable declaration and initialization done within the loop.
