### ISSUE TITLE
Check if window.onload is required

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/english-to-braille-js-assignment-problem-vermarahul18#2]
https://github.com/sro-boeing-wave-2/english-to-braille-js-assignment-problem-vermarahul18/blob/61103b74ae6c501529ba9b98edd24ba617c0344f/index.js#L22-L25

**Comment by nishant-jain-94** [comment]
Line 23 and Line 24 can be chained using dot operator

**Comment by vermarahul18** [comment]
Combined Line 23 and 24 using dot operator. Placed it at the top after removing the windows.onload () function.
