### ISSUE TITLE
Use es6 Array.prototype.map instead of using for loop

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/english-to-braille-js-assignment-problem-vermarahul18#3]
https://github.com/sro-boeing-wave-2/english-to-braille-js-assignment-problem-vermarahul18/blob/61103b74ae6c501529ba9b98edd24ba617c0344f/index.js#L16-L18

**Comment by nishant-jain-94** [comment]
Array.prototype.map can be referred here from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Map

**Comment by vermarahul18** [comment]
Used the es6 array.prototype.map .
